[defaults]
destination = "mac"
extra_args = []
skip_plugin_validation = true

[defaults.build]
scheme = "MetalSprockets-Example"

[defaults.test]
scheme = "MetalSprockets"

[defaults.run]
scheme = "MetalSprockets-Example"

[output]

[new.blueprint_defaults]
