import Metal
import MetalSprockets
import MetalSprocketsSupport
import simd

// Element is like SwiftUI View but for Metal
struct DemoCubeRenderPipeline: Element {
    let shaderLibrary: ShaderLibrary
    let transform: float4x4
    let time: Float

    init(transform: float4x4, time: Float) throws {
        // ShaderLibrary generated by @ShaderLibrary macro - type-safe access to .metal shaders
        self.shaderLibrary = try ShaderLibrary(bundle: .main)
        self.transform = transform
        self.time = time
    }

    var body: some Element {
        get throws {
            // RenderPipeline binds shaders and configures pipeline state
            try RenderPipeline(label: "Vertex-Colored Cube", vertexShader: shaderLibrary.vertexMain, fragmentShader: shaderLibrary.fragmentMain) {
                // Draw gives direct access to the Metal 4 render encoder; the pipeline and inputs are already bound.
                Draw { encoder in
                    encoder.drawPrimitives(primitiveType: .triangle, vertexStart: 0, vertexCount: cubeVertexCount)
                }
                // Metal 4 has no setVertexBytes: small vertex data goes through scratch storage.
                .vertexValues(generateCubeVertices(), index: 0)
                // Bind shader uniforms by name via reflection — no hardcoded buffer indices.
                .parameter("transform", value: transform)
                .parameter("time", value: time)
            }
            // Tells Metal how to interpret Vertex struct
            .vertexDescriptor(Vertex.descriptor)
            .depthCompare(function: .less, enabled: true)
        }
    }
}
